### ISSUE TITLE
Terminar de crear los xml de hibernete

### ISSUE THREAD

**Issue by loiaconopablo** [DesarrolloDeAplicaciones-GrupoA/backend#1]

**Comment by leandro-gomez** [comment]
Si bien el titulo dice "xml", em gustaria usar annotations, tanto para hibernate, como para los servicios.
Con estoy evitamos la duplicacion de configuracion y  la simplificamos.

Hay un branch (use-annotations) el cual tiene una minima implementacion, donde todos los tests pasan y hay un minimo de mappings hecho con anotations.

Que les parece? @loiaconopablo @damianlattenero ??

**Comment by damian-rafael-lattenero** [comment]
Bien, el profe en un punto prefería utilizar xml sobre anotations, no sé
bien donde

**Comment by leandro-gomez** [comment]
Bueno, que les parece si mando un email explicando la situacion y vemos que responden (SI responden)

que les parece?

**Comment by damian-rafael-lattenero** [comment]
Bárbaro, sino responden, hagamos lo que nos convenga. Y si chillan, yo les
digo que nunca contestaron, vos tranquilo. Hagamos lo mejor, confio en tu
experiencia

**Comment by leandro-gomez** [comment]
Usamos annotations
